//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeEcommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbShopeeEcommerceEntities : DbContext
    {
        public dbShopeeEcommerceEntities()
            : base("name=dbShopeeEcommerceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TShopeeCustomer> TShopeeCustomers { get; set; }
        public virtual DbSet<TShopeeInvoice> TShopeeInvoices { get; set; }
        public virtual DbSet<TShopeeInvoiceStatu> TShopeeInvoiceStatus { get; set; }
        public virtual DbSet<TShopeeOrder> TShopeeOrders { get; set; }
        public virtual DbSet<TShopeeOrderItem> TShopeeOrderItems { get; set; }
        public virtual DbSet<TShopeeOrderItemStatu> TShopeeOrderItemStatus { get; set; }
        public virtual DbSet<TShopeeOrderStatu> TShopeeOrderStatus { get; set; }
        public virtual DbSet<TShopeePaymentMethod> TShopeePaymentMethods { get; set; }
        public virtual DbSet<TShopeePlatform> TShopeePlatforms { get; set; }
    
        public virtual int NSP_TShopeeCustomer_Delete(Nullable<int> customer_id)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCustomer_Delete", customer_idParameter);
        }
    
        public virtual int NSP_TShopeeCustomer_Insert(string first_name, string last_name, Nullable<System.DateTime> dob, string email_address, string phone_number, string address_line_1, string address_line_2, string city, string state, Nullable<int> zip_code, string country, Nullable<int> platform_id)
        {
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var address_line_1Parameter = address_line_1 != null ?
                new ObjectParameter("address_line_1", address_line_1) :
                new ObjectParameter("address_line_1", typeof(string));
    
            var address_line_2Parameter = address_line_2 != null ?
                new ObjectParameter("address_line_2", address_line_2) :
                new ObjectParameter("address_line_2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zip_codeParameter = zip_code.HasValue ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCustomer_Insert", first_nameParameter, last_nameParameter, dobParameter, email_addressParameter, phone_numberParameter, address_line_1Parameter, address_line_2Parameter, cityParameter, stateParameter, zip_codeParameter, countryParameter, platform_idParameter);
        }
    
        public virtual int NSP_TShopeeCustomer_Update(Nullable<int> customer_id, string first_name, string last_name, Nullable<System.DateTime> dob, string email_address, string phone_number, string address_line_1, string address_line_2, string city, string state, Nullable<int> zip_code, string country, Nullable<int> platform_id)
        {
            var customer_idParameter = customer_id.HasValue ?
                new ObjectParameter("customer_id", customer_id) :
                new ObjectParameter("customer_id", typeof(int));
    
            var first_nameParameter = first_name != null ?
                new ObjectParameter("first_name", first_name) :
                new ObjectParameter("first_name", typeof(string));
    
            var last_nameParameter = last_name != null ?
                new ObjectParameter("last_name", last_name) :
                new ObjectParameter("last_name", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var email_addressParameter = email_address != null ?
                new ObjectParameter("email_address", email_address) :
                new ObjectParameter("email_address", typeof(string));
    
            var phone_numberParameter = phone_number != null ?
                new ObjectParameter("phone_number", phone_number) :
                new ObjectParameter("phone_number", typeof(string));
    
            var address_line_1Parameter = address_line_1 != null ?
                new ObjectParameter("address_line_1", address_line_1) :
                new ObjectParameter("address_line_1", typeof(string));
    
            var address_line_2Parameter = address_line_2 != null ?
                new ObjectParameter("address_line_2", address_line_2) :
                new ObjectParameter("address_line_2", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("city", city) :
                new ObjectParameter("city", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(string));
    
            var zip_codeParameter = zip_code.HasValue ?
                new ObjectParameter("zip_code", zip_code) :
                new ObjectParameter("zip_code", typeof(int));
    
            var countryParameter = country != null ?
                new ObjectParameter("country", country) :
                new ObjectParameter("country", typeof(string));
    
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeCustomer_Update", customer_idParameter, first_nameParameter, last_nameParameter, dobParameter, email_addressParameter, phone_numberParameter, address_line_1Parameter, address_line_2Parameter, cityParameter, stateParameter, zip_codeParameter, countryParameter, platform_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoice_Delete(Nullable<int> invoice_id)
        {
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoice_Delete", invoice_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoice_Insert(Nullable<System.DateTime> invoice_date, string invoice_details, Nullable<decimal> shipping_fee, Nullable<int> payment_method_id, Nullable<int> invoice_status_id)
        {
            var invoice_dateParameter = invoice_date.HasValue ?
                new ObjectParameter("invoice_date", invoice_date) :
                new ObjectParameter("invoice_date", typeof(System.DateTime));
    
            var invoice_detailsParameter = invoice_details != null ?
                new ObjectParameter("invoice_details", invoice_details) :
                new ObjectParameter("invoice_details", typeof(string));
    
            var shipping_feeParameter = shipping_fee.HasValue ?
                new ObjectParameter("shipping_fee", shipping_fee) :
                new ObjectParameter("shipping_fee", typeof(decimal));
    
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoice_Insert", invoice_dateParameter, invoice_detailsParameter, shipping_feeParameter, payment_method_idParameter, invoice_status_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoice_Update(Nullable<int> invoice_id, Nullable<System.DateTime> invoice_date, string invoice_details, Nullable<decimal> shipping_fee, Nullable<int> payment_method_id, Nullable<int> invoice_status_id)
        {
            var invoice_idParameter = invoice_id.HasValue ?
                new ObjectParameter("invoice_id", invoice_id) :
                new ObjectParameter("invoice_id", typeof(int));
    
            var invoice_dateParameter = invoice_date.HasValue ?
                new ObjectParameter("invoice_date", invoice_date) :
                new ObjectParameter("invoice_date", typeof(System.DateTime));
    
            var invoice_detailsParameter = invoice_details != null ?
                new ObjectParameter("invoice_details", invoice_details) :
                new ObjectParameter("invoice_details", typeof(string));
    
            var shipping_feeParameter = shipping_fee.HasValue ?
                new ObjectParameter("shipping_fee", shipping_fee) :
                new ObjectParameter("shipping_fee", typeof(decimal));
    
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoice_Update", invoice_idParameter, invoice_dateParameter, invoice_detailsParameter, shipping_feeParameter, payment_method_idParameter, invoice_status_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoiceStatus_Delete(Nullable<int> invoice_status_id)
        {
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoiceStatus_Delete", invoice_status_idParameter);
        }
    
        public virtual int NSP_TShopeeInvoiceStatus_Insert(string name, string description)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoiceStatus_Insert", nameParameter, descriptionParameter);
        }
    
        public virtual int NSP_TShopeeInvoiceStatus_Update(Nullable<int> invoice_status_id, string name, string description)
        {
            var invoice_status_idParameter = invoice_status_id.HasValue ?
                new ObjectParameter("invoice_status_id", invoice_status_id) :
                new ObjectParameter("invoice_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeInvoiceStatus_Update", invoice_status_idParameter, nameParameter, descriptionParameter);
        }
    
        public virtual int NSP_TShopeeOrder_Delete(Nullable<int> order_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrder_Delete", order_idParameter);
        }
    
        public virtual int NSP_TShopeeOrder_Insert(Nullable<System.DateTime> order_placed_date, Nullable<decimal> total_price, Nullable<int> order_status_id)
        {
            var order_placed_dateParameter = order_placed_date.HasValue ?
                new ObjectParameter("order_placed_date", order_placed_date) :
                new ObjectParameter("order_placed_date", typeof(System.DateTime));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrder_Insert", order_placed_dateParameter, total_priceParameter, order_status_idParameter);
        }
    
        public virtual int NSP_TShopeeOrder_Update(Nullable<int> order_id, Nullable<System.DateTime> order_placed_date, Nullable<decimal> total_price, Nullable<int> order_status_id)
        {
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var order_placed_dateParameter = order_placed_date.HasValue ?
                new ObjectParameter("order_placed_date", order_placed_date) :
                new ObjectParameter("order_placed_date", typeof(System.DateTime));
    
            var total_priceParameter = total_price.HasValue ?
                new ObjectParameter("total_price", total_price) :
                new ObjectParameter("total_price", typeof(decimal));
    
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrder_Update", order_idParameter, order_placed_dateParameter, total_priceParameter, order_status_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItem_Delete(Nullable<int> order_item_id)
        {
            var order_item_idParameter = order_item_id.HasValue ?
                new ObjectParameter("order_item_id", order_item_id) :
                new ObjectParameter("order_item_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItem_Delete", order_item_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItem_Insert(Nullable<int> quantity, Nullable<decimal> sub_total, Nullable<decimal> discount_fee, Nullable<int> rMA_num, string rMA_issued_by, Nullable<System.DateTime> rMA_issued_date, Nullable<int> order_id, Nullable<int> order_item_status_id, Nullable<int> product_id)
        {
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var sub_totalParameter = sub_total.HasValue ?
                new ObjectParameter("sub_total", sub_total) :
                new ObjectParameter("sub_total", typeof(decimal));
    
            var discount_feeParameter = discount_fee.HasValue ?
                new ObjectParameter("discount_fee", discount_fee) :
                new ObjectParameter("discount_fee", typeof(decimal));
    
            var rMA_numParameter = rMA_num.HasValue ?
                new ObjectParameter("RMA_num", rMA_num) :
                new ObjectParameter("RMA_num", typeof(int));
    
            var rMA_issued_byParameter = rMA_issued_by != null ?
                new ObjectParameter("RMA_issued_by", rMA_issued_by) :
                new ObjectParameter("RMA_issued_by", typeof(string));
    
            var rMA_issued_dateParameter = rMA_issued_date.HasValue ?
                new ObjectParameter("RMA_issued_date", rMA_issued_date) :
                new ObjectParameter("RMA_issued_date", typeof(System.DateTime));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItem_Insert", quantityParameter, sub_totalParameter, discount_feeParameter, rMA_numParameter, rMA_issued_byParameter, rMA_issued_dateParameter, order_idParameter, order_item_status_idParameter, product_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItem_Update(Nullable<int> order_item_id, Nullable<int> quantity, Nullable<decimal> sub_total, Nullable<decimal> discount_fee, Nullable<int> rMA_num, string rMA_issued_by, Nullable<System.DateTime> rMA_issued_date, Nullable<int> order_id, Nullable<int> order_item_status_id, Nullable<int> product_id)
        {
            var order_item_idParameter = order_item_id.HasValue ?
                new ObjectParameter("order_item_id", order_item_id) :
                new ObjectParameter("order_item_id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var sub_totalParameter = sub_total.HasValue ?
                new ObjectParameter("sub_total", sub_total) :
                new ObjectParameter("sub_total", typeof(decimal));
    
            var discount_feeParameter = discount_fee.HasValue ?
                new ObjectParameter("discount_fee", discount_fee) :
                new ObjectParameter("discount_fee", typeof(decimal));
    
            var rMA_numParameter = rMA_num.HasValue ?
                new ObjectParameter("RMA_num", rMA_num) :
                new ObjectParameter("RMA_num", typeof(int));
    
            var rMA_issued_byParameter = rMA_issued_by != null ?
                new ObjectParameter("RMA_issued_by", rMA_issued_by) :
                new ObjectParameter("RMA_issued_by", typeof(string));
    
            var rMA_issued_dateParameter = rMA_issued_date.HasValue ?
                new ObjectParameter("RMA_issued_date", rMA_issued_date) :
                new ObjectParameter("RMA_issued_date", typeof(System.DateTime));
    
            var order_idParameter = order_id.HasValue ?
                new ObjectParameter("order_id", order_id) :
                new ObjectParameter("order_id", typeof(int));
    
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItem_Update", order_item_idParameter, quantityParameter, sub_totalParameter, discount_feeParameter, rMA_numParameter, rMA_issued_byParameter, rMA_issued_dateParameter, order_idParameter, order_item_status_idParameter, product_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItemStatus_Delete(Nullable<int> order_item_status_id)
        {
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItemStatus_Delete", order_item_status_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderItemStatus_Insert(string name, string description, Nullable<int> return_merchandise_authorization_nr)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var return_merchandise_authorization_nrParameter = return_merchandise_authorization_nr.HasValue ?
                new ObjectParameter("return_merchandise_authorization_nr", return_merchandise_authorization_nr) :
                new ObjectParameter("return_merchandise_authorization_nr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItemStatus_Insert", nameParameter, descriptionParameter, return_merchandise_authorization_nrParameter);
        }
    
        public virtual int NSP_TShopeeOrderItemStatus_Update(Nullable<int> order_item_status_id, string name, string description, Nullable<int> return_merchandise_authorization_nr)
        {
            var order_item_status_idParameter = order_item_status_id.HasValue ?
                new ObjectParameter("order_item_status_id", order_item_status_id) :
                new ObjectParameter("order_item_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var return_merchandise_authorization_nrParameter = return_merchandise_authorization_nr.HasValue ?
                new ObjectParameter("return_merchandise_authorization_nr", return_merchandise_authorization_nr) :
                new ObjectParameter("return_merchandise_authorization_nr", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderItemStatus_Update", order_item_status_idParameter, nameParameter, descriptionParameter, return_merchandise_authorization_nrParameter);
        }
    
        public virtual int NSP_TShopeeOrderStatus_Delete(Nullable<int> order_status_id)
        {
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderStatus_Delete", order_status_idParameter);
        }
    
        public virtual int NSP_TShopeeOrderStatus_Insert(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderStatus_Insert", nameParameter);
        }
    
        public virtual int NSP_TShopeeOrderStatus_Update(Nullable<int> order_status_id, string name)
        {
            var order_status_idParameter = order_status_id.HasValue ?
                new ObjectParameter("order_status_id", order_status_id) :
                new ObjectParameter("order_status_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeeOrderStatus_Update", order_status_idParameter, nameParameter);
        }
    
        public virtual int NSP_TShopeePaymentMethod_Delete(Nullable<int> payment_method_id)
        {
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePaymentMethod_Delete", payment_method_idParameter);
        }
    
        public virtual int NSP_TShopeePaymentMethod_Insert(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePaymentMethod_Insert", nameParameter);
        }
    
        public virtual int NSP_TShopeePaymentMethod_Update(Nullable<int> payment_method_id, string name)
        {
            var payment_method_idParameter = payment_method_id.HasValue ?
                new ObjectParameter("payment_method_id", payment_method_id) :
                new ObjectParameter("payment_method_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePaymentMethod_Update", payment_method_idParameter, nameParameter);
        }
    
        public virtual int NSP_TShopeePlatform_Delete(Nullable<int> platform_id)
        {
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePlatform_Delete", platform_idParameter);
        }
    
        public virtual int NSP_TShopeePlatform_Insert(string name)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePlatform_Insert", nameParameter);
        }
    
        public virtual int NSP_TShopeePlatform_Update(Nullable<int> platform_id, string name)
        {
            var platform_idParameter = platform_id.HasValue ?
                new ObjectParameter("platform_id", platform_id) :
                new ObjectParameter("platform_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("NSP_TShopeePlatform_Update", platform_idParameter, nameParameter);
        }
    }
}
