//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeOrderItem
    {
        public int order_item_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> discount_fee { get; set; }
        public Nullable<int> RMA_num { get; set; }
        public string RMA_issued_by { get; set; }
        public Nullable<System.DateTime> RMA_issued_date { get; set; }
        public Nullable<int> order_id { get; set; }
        public Nullable<int> order_item_status_id { get; set; }
        public Nullable<int> product_id { get; set; }
    }
}
