//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbShopeeEcommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TShopeeOrderItemStatu
    {
        public int order_item_status_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> return_merchandise_authorization_nr { get; set; }
    }
}
